import { useState } from "react";
// Removed Firebase and function imports

// --- STYLES & ANIMATIONS ---
const KeyframeStyles = () => (
    <style>
        {`
      @keyframes shimmer {
        0% {
          background-position: -200% 0;
        }
        100% {
          background-position: 200% 0;
        }
      }
      
      @keyframes fadeIn {
        from {
          opacity: 0;
          transform: translateY(20px);
        }
        to {
          opacity: 1;
          transform: translateY(0);
        }
      }
      
      @keyframes iconFloat {
        0% {
          transform: translateY(0px);
        }
        50% {
          transform: translateY(-15px);
        }
        100% {
          transform: translateY(0px);
        }
      }
    `}
    </style>
);

// --- SUB-COMPONENT: Animated Button ---
const NotifyButton = () => {
    const [hover, setHover] = useState(false);

    const style = {
        marginTop: "16px",
        padding: "16px 32px",
        color: "white",
        borderRadius: "8px",
        border: "none",
        cursor: "pointer",
        fontSize: "1rem",
        fontWeight: "600",
        transition: "all 0.3s ease-in-out",
        position: "relative",
        overflow: "hidden",

        // Dynamic styles
        background: (hover
            ? "rgba(140, 100, 255, 1)"
            : "rgba(140, 100, 255, 0.8)"),
        boxShadow: hover
            ? "0 0 20px rgba(140, 100, 255, 0.5)"
            : "none",
        transform: hover ? "translateY(-2px)" : "translateY(0)",
    };

    const shimmerStyle = {
        position: "absolute", top: 0, left: 0, width: "100%", height: "100%",
        background: "linear-gradient(90deg, transparent, rgba(255,255,255,0.3), transparent)",
        backgroundSize: "400% 100%", animation: "shimmer 3s infinite linear",
        opacity: hover ? 1 : 0, transition: "opacity 0.3s"
    };

    return (
        <button
            style={style}
            onMouseEnter={() => setHover(true)}
            onMouseLeave={() => setHover(false)}
            onClick={() => alert("You'll be the first to know when scheduling is live!")}
        >
            <div style={shimmerStyle}></div>
            Notify Me When Scheduling is Live
        </button>
    );
};

// --- MAIN COMPONENT: AutomationPage ---
export default function AutomationPage() {

    // --- Main Styles ---
    const pageStyle = {
        padding: "40px",
        maxWidth: "900px",
        margin: "40px auto 0 auto",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    };

    const panelStyle = {
        // --- Glassmorphism ---
        background: "rgba(35, 35, 45, 0.5)",
        backdropFilter: "blur(20px)",
        WebkitBackdropFilter: "blur(20px)",
        border: "1px solid rgba(255, 255, 255, 0.1)",

        borderRadius: "16px",
        padding: "48px",
        textAlign: "center",
        width: "100%",
        maxWidth: "600px",
        boxShadow: "0 10px 30px rgba(0, 0, 0, 0.3)",
        animation: "fadeIn 0.7s ease-out",
    };

    const iconStyle = {
        fontSize: "4rem",
        marginBottom: "24px",
        display: "inline-block",
        animation: "iconFloat 3s ease-in-out infinite",
    };

    const titleStyle = {
        fontSize: "2.25rem",
        fontWeight: "700",
        color: "#ffffff",
        marginBottom: "16px",
        letterSpacing: "-1px"
    };

    const descriptionStyle = {
        fontSize: "1rem",
        color: "#a0a0b0",
        lineHeight: "1.6",
        maxWidth: "450px",
        margin: "0 auto 32px auto"
    };

    return (
        <div style={pageStyle}>
            <KeyframeStyles />

            <div style={panelStyle}>
                <div style={iconStyle}>🤖</div>

                <h1 style={titleStyle}>Automate Your Socials</h1>

                <p style={descriptionStyle}>
                    **Auto-posting and Scheduling is coming soon!**
                    <br /><br />
                    You'll be able to connect your Instagram, Twitter, Facebook, LinkedIn, and Pinterest
                    accounts to our platform to schedule and auto-post the content
                    generated by your AI Guide.
                </p>

                <NotifyButton />
            </div>
        </div>
    );
}